# Site settings
title: "kerlingNote"
email: 33724041@qq.com
description: > # this means to ignore newlines until "baseurl:"
  enjoy your hack
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kerlingcode.github.io" # the base hostname & protocol for your site
twitter_username: kerling
github_username:  kerling

# Build settings
markdown: kramdown
permalink: ":title/"
highlighter: pygments

# Pagination
paginate: 10
paginate_path: "blog/page/:num/"

# Minification
sass:
  style: compressed
